[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # Expose the GOOGLE_API_KEY as VITE_GOOGLE_API_KEY during build
  VITE_GOOGLE_API_KEY = "${GOOGLE_API_KEY}"

[functions]
  directory = "netlify/functions"

[dev]
  command = "vite"
  targetPort = 3000
  port = 8888
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200