[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

[dev]
  command = "vite"
  targetPort = 3000
  port = 8888
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
