[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

[dev]
  command = "vite"
  targetPort = 3000
  port = 8888
  framework = "vite"

# For local development only - these won't be deployed
[dev.environment]
  # For local development with netlify dev
  # Note: You should set actual values in the Netlify UI for production
  WEATHER_API_KEY = ""
  GOOGLE_API_KEY = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200